const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const err=(message,status=400)=>json({error:message},status);
const uuid=()=>crypto.randomUUID();
const enc=new TextEncoder();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const unhex=s=>new Uint8Array((s.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
const timingSafe=(a,b)=>{if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const cookie=(name,value,maxAge=60*60*24*30)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const clearCookie=name=>`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
const getCookie=(req,name)=>{const c=req.headers.get('cookie')||'';const m=c.match(new RegExp(`(?:^|; )${name}=([^;]*)`));return m?decodeURIComponent(m[1]):null};
async function hashPassword(password,saltHex){const salt=saltHex?unhex(saltHex):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},key,256);return {salt:hex(salt),hash:hex(bits)}}
async function sha256(s){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function body(req){try{return await req.json()}catch{return {}}}
async function userFromRequest(req,env){const token=getCookie(req,'ba_session');if(!token)return null;const tokenHash=await sha256(token);const row=await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).bind(tokenHash).first();return row||null}
const publicUser=u=>({id:u.id,email:u.email,full_name:u.full_name,company_name:u.company_name,phone:u.phone,country:u.country,preferred_language:u.preferred_language,plan:u.plan,status:u.status,is_admin:!!u.is_admin,email_verified:!!u.email_verified,created_at:u.created_at,subscription_status:u.subscription_status||'none',current_period_end:u.current_period_end||null});
async function requireUser(req,env){const u=await userFromRequest(req,env);if(!u)throw new Response(JSON.stringify({error:'Authentication required'}),{status:401,headers:{'content-type':'application/json'}});return u}
async function requireAdmin(req,env){const u=await requireUser(req,env);if(!u.is_admin)throw new Response(JSON.stringify({error:'Admin access required'}),{status:403,headers:{'content-type':'application/json'}});return u}
const planMap={starter:{name:'Starter',price:49},growth:{name:'Growth',price:99},business:{name:'Business',price:159},enterprise:{name:'Enterprise',price:259}};
function pdfEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function makeInvoicePdf(inv){const lines=[
'BALKANAGENT V3 ENTERPRISE',
'DOO Balkan Agent',
'Djerane II b.b., Ulcinj, Crna Gora',
'Email: Fariz.suljevic@gmail.com',
'',
`Racun / Invoice: ${inv.invoice_number}`,
`Datum / Date: ${inv.issued_at.slice(0,10)}`,
`Kupac / Customer: ${inv.customer_name||inv.customer_email}`,
`Email: ${inv.customer_email}`,
`Paket / Plan: ${planMap[inv.plan]?.name||inv.plan}`,
'',
`Iznos / Amount: EUR ${(inv.amount_cents/100).toFixed(2)}`,
`Status: ${inv.status}`,
'',
'Hvala sto koristite BalkanAgent.'
];let y=790;const ops=['BT','/F1 14 Tf'];for(const [i,l] of lines.entries()){ops.push(`1 0 0 1 55 ${y} Tm (${pdfEscape(l)}) Tj`);y-=i===0?30:22}ops.push('ET');const stream=ops.join('\n');const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objects[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>';objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[5]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;let out='%PDF-1.4\n';const offsets=[0];for(let i=1;i<=5;i++){offsets[i]=out.length;out+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=out.length;out+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)out+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Response(out,{headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="${inv.invoice_number}.pdf"`}})}
async function stripeRequest(env,path,params){if(!env.STRIPE_SECRET_KEY)throw new Error('Stripe is not configured. Add STRIPE_SECRET_KEY and price IDs in Cloudflare.');const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'Stripe request failed');return d}
async function verifyStripe(req,env,raw){if(!env.STRIPE_WEBHOOK_SECRET)return false;const sig=req.headers.get('stripe-signature')||'';const t=(sig.match(/(?:^|,)t=([^,]+)/)||[])[1];const signatures=[...sig.matchAll(/(?:^|,)v1=([^,]+)/g)].map(m=>m[1]);if(!t||!signatures.length)return false;const ts=Number(t);if(!Number.isFinite(ts)||Math.abs(Math.floor(Date.now()/1000)-ts)>300)return false;const key=await crypto.subtle.importKey('raw',enc.encode(env.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,enc.encode(`${t}.${raw}`));const expected=hex(signed);return signatures.some(v=>timingSafe(expected,v))}
export async function onRequest(context){const {request:req,env}=context;const url=new URL(req.url);const path='/'+(context.params.path||[]).join('/');const method=req.method;
try{
 if(path==='/auth/admin-setup'&&method==='POST'){const b=await body(req);const email=String(b.email||'').trim().toLowerCase();const fullName=String(b.fullName||'Fariz Suljevic').trim();const password=String(b.password||'');const setupKey=String(b.setupKey||'');const adminEmail=String(env.ADMIN_EMAIL||'fariz.suljevic@gmail.com').trim().toLowerCase();if(!env.ADMIN_SETUP_KEY)return err('ADMIN_SETUP_KEY is not configured in Cloudflare.',503);if(!timingSafe(setupKey,String(env.ADMIN_SETUP_KEY)))return err('Invalid administrator setup key.',403);if(email!==adminEmail)return err('This email is not allowed for administrator setup.',403);if(password.length<10||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password))return err('Password must be at least 10 characters and include uppercase, lowercase and a number.');const hp=await hashPassword(password);let u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(u){await env.DB.prepare(`UPDATE users SET password_hash=?,password_salt=?,full_name=?,is_admin=1,status='active',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(hp.hash,hp.salt,fullName,u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(u.id).first()}else{const id=uuid();await env.DB.prepare(`INSERT INTO users(id,email,password_hash,password_salt,full_name,company_name,preferred_language,plan,status,is_admin) VALUES(?,?,?,?,?,?,?,?,?,1)`).bind(id,email,hp.hash,hp.salt,fullName,'DOO Balkan Agent','bs','enterprise','active').run();u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first()}const token=uuid()+uuid();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))`).bind(await sha256(token),u.id).run();return json({ok:true,is_admin:true,user:publicUser(u)},200,{'set-cookie':cookie('ba_session',token)})}
 if(path==='/auth/register'&&method==='POST'){const b=await body(req);const email=String(b.email||'').trim().toLowerCase();const fullName=String(b.fullName||'').trim();const password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return err('Enter a valid email address.');if(fullName.length<2)return err('Full name is required.');if(password.length<10)return err('Password must contain at least 10 characters.');if(!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password))return err('Password must include uppercase, lowercase and a number.');const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(exists)return err('An account with this email already exists.',409);const hp=await hashPassword(password);const id=uuid();await env.DB.prepare(`INSERT INTO users(id,email,password_hash,password_salt,full_name,company_name,preferred_language,plan,status) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,email,hp.hash,hp.salt,fullName,String(b.companyName||''),String(b.preferredLanguage||'en'),'starter','pending').run();const token=uuid()+uuid();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))`).bind(await sha256(token),id).run();return json({ok:true},201,{'set-cookie':cookie('ba_session',token)})}
 if(path==='/auth/login'&&method==='POST'){const b=await body(req);const email=String(b.email||'').trim().toLowerCase();const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u)return err('Invalid email or password.',401);const hp=await hashPassword(String(b.password||''),u.password_salt);if(!timingSafe(hp.hash,u.password_hash))return err('Invalid email or password.',401);if(u.status==='suspended')return err('This account is suspended.',403);const token=uuid()+uuid();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))`).bind(await sha256(token),u.id).run();return json({ok:true,is_admin:!!u.is_admin,user:publicUser(u)},200,{'set-cookie':cookie('ba_session',token)})}
 if(path==='/auth/logout'&&method==='POST'){const token=getCookie(req,'ba_session');if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run();return json({ok:true},200,{'set-cookie':clearCookie('ba_session')})}
 if(path==='/auth/me'&&method==='GET'){const u=await requireUser(req,env);return json({user:publicUser(u)})}
 if(path==='/auth/password'&&method==='POST'){const u=await requireUser(req,env);const b=await body(req);const password=String(b.password||'');if(password.length<10)return err('Password must contain at least 10 characters.');const hp=await hashPassword(password);await env.DB.prepare(`UPDATE users SET password_hash=?,password_salt=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(hp.hash,hp.salt,u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();return json({ok:true},200,{'set-cookie':clearCookie('ba_session')})}
 if(path==='/profile'&&method==='GET'){const u=await requireUser(req,env);return json({user:publicUser(u)})}
 if(path==='/profile'&&method==='PUT'){const u=await requireUser(req,env);const b=await body(req);await env.DB.prepare(`UPDATE users SET full_name=?,company_name=?,phone=?,country=?,preferred_language=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(String(b.fullName||u.full_name),String(b.companyName||''),String(b.phone||''),String(b.country||''),String(b.preferredLanguage||'en'),u.id).run();return json({ok:true})}
 if(path==='/agents'&&method==='GET'){const u=await requireUser(req,env);const d=await env.DB.prepare('SELECT * FROM ai_agents WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all();return json({items:d.results||[]})}
 if(path==='/agents'&&method==='POST'){const u=await requireUser(req,env);const b=await body(req);if(!b.name||!b.role)return err('Name and role are required.');await env.DB.prepare(`INSERT INTO ai_agents(id,user_id,name,role,language,status,instructions) VALUES(?,?,?,?,?,'active',?)`).bind(uuid(),u.id,String(b.name),String(b.role),String(b.language||'en'),String(b.instructions||'')).run();return json({ok:true})}
 if(path==='/bookings'&&method==='GET'){const u=await requireUser(req,env);const d=await env.DB.prepare('SELECT * FROM bookings WHERE user_id=? ORDER BY booking_date DESC').bind(u.id).all();return json({items:d.results||[]})}
 if(path==='/bookings'&&method==='POST'){const u=await requireUser(req,env);const b=await body(req);if(!b.customerName||!b.service||!b.bookingDate)return err('Customer, service and date are required.');await env.DB.prepare(`INSERT INTO bookings(id,user_id,customer_name,customer_email,service,booking_date,status,notes) VALUES(?,?,?,?,?,?,'pending',?)`).bind(uuid(),u.id,String(b.customerName),String(b.customerEmail||''),String(b.service),String(b.bookingDate),String(b.notes||'')).run();return json({ok:true})}
 if(path==='/conversations'&&method==='GET'){const u=await requireUser(req,env);const d=await env.DB.prepare(`SELECT c.*,a.name agent_name FROM conversations c LEFT JOIN ai_agents a ON a.id=c.agent_id WHERE c.user_id=? ORDER BY c.created_at DESC`).bind(u.id).all();return json({items:d.results||[]})}
 if(path==='/admin/stats'&&method==='GET'){await requireAdmin(req,env);const rows=await env.DB.prepare(`SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM users WHERE status='active') active,(SELECT COUNT(*) FROM users WHERE status='pending') pending,(SELECT COUNT(*) FROM ai_agents) agents,(SELECT COUNT(*) FROM conversations) conversations,(SELECT COUNT(*) FROM bookings) bookings,(SELECT COUNT(*) FROM invoices) invoices`).first();return json(rows)}
 if(path==='/admin/users'&&method==='GET'){await requireAdmin(req,env);const d=await env.DB.prepare(`SELECT id,email,full_name,company_name,plan,status,is_admin,subscription_status,current_period_end,created_at FROM users ORDER BY created_at DESC`).all();return json({items:d.results||[]})}
 if(path==='/admin/users'&&method==='PATCH'){const admin=await requireAdmin(req,env);const b=await body(req);const status=String(b.status||'');const plan=String(b.plan||'');const id=String(b.id||'');if(!id)return err('User ID is required.');if(!['active','pending','suspended'].includes(status))return err('Invalid status.');if(!planMap[plan])return err('Invalid plan.');if(id===admin.id&&status!=='active')return err('You cannot suspend your own administrator account.');const result=await env.DB.prepare('UPDATE users SET status=?,plan=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,plan,id).run();if(!result.meta?.changes)return err('User not found.',404);return json({ok:true})}
 if(path==='/billing/plans'&&method==='GET'){return json({plans:Object.entries(planMap).map(([id,p])=>({id,...p}))})}
 if(path==='/billing/checkout'&&method==='POST'){const u=await requireUser(req,env);const b=await body(req);const plan=String(b.plan||'');if(!planMap[plan])return err('Invalid plan.');const envName='STRIPE_PRICE_'+plan.toUpperCase();const priceId=env[envName];if(!priceId)return err(`Stripe price is missing: ${envName}`,503);const origin=url.origin;const data=await stripeRequest(env,'checkout/sessions',{mode:'subscription','line_items[0][price]':priceId,'line_items[0][quantity]':'1','customer_email':u.email,'client_reference_id':u.id,'metadata[user_id]':u.id,'metadata[plan]':plan,success_url:`${origin}/billing.html?success=1`,cancel_url:`${origin}/billing.html?cancel=1`,allow_promotion_codes:'true'});return json({url:data.url})}
 if(path==='/billing/invoices'&&method==='GET'){const u=await requireUser(req,env);const d=await env.DB.prepare('SELECT * FROM invoices WHERE user_id=? ORDER BY issued_at DESC').bind(u.id).all();return json({items:d.results||[]})}
 if(path.startsWith('/billing/invoices/')&&path.endsWith('/pdf')&&method==='GET'){const u=await requireUser(req,env);const id=path.split('/')[3];const inv=await env.DB.prepare('SELECT * FROM invoices WHERE id=? AND (user_id=? OR ?=1)').bind(id,u.id,u.is_admin?1:0).first();if(!inv)return err('Invoice not found.',404);return makeInvoicePdf(inv)}
 if(path==='/stripe/webhook'&&method==='POST'){const raw=await req.text();if(!await verifyStripe(req,env,raw))return err('Invalid Stripe signature.',400);const event=JSON.parse(raw);if(event.type==='checkout.session.completed'){const s=event.data.object;const userId=s.client_reference_id||s.metadata?.user_id;const plan=s.metadata?.plan||'starter';await env.DB.prepare(`UPDATE users SET plan=?,status='active',subscription_status='active',stripe_customer_id=?,stripe_subscription_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(plan,String(s.customer||''),String(s.subscription||''),userId).run()}
 if(event.type==='invoice.paid'||event.type==='invoice.payment_succeeded'){const i=event.data.object;const u=await env.DB.prepare('SELECT * FROM users WHERE stripe_customer_id=?').bind(String(i.customer||'')).first();if(u){const num=i.number||`BA-${new Date().getFullYear()}-${String(i.created||Date.now()).slice(-8)}`;await env.DB.prepare(`INSERT OR IGNORE INTO invoices(id,user_id,stripe_invoice_id,invoice_number,customer_name,customer_email,plan,amount_cents,currency,status,issued_at) VALUES(?,?,?,?,?,?,?,?,?,'paid',datetime(?,'unixepoch'))`).bind(uuid(),u.id,String(i.id),num,u.company_name||u.full_name,u.email,u.plan,Number(i.amount_paid||0),String(i.currency||'eur').toUpperCase(),Number(i.created||Math.floor(Date.now()/1000))).run()}}
 if(event.type==='customer.subscription.updated'){const o=event.data.object;const customer=String(o.customer||'');const periodEnd=o.current_period_end?new Date(Number(o.current_period_end)*1000).toISOString():null;await env.DB.prepare(`UPDATE users SET subscription_status=?,stripe_subscription_id=?,current_period_end=?,updated_at=CURRENT_TIMESTAMP WHERE stripe_customer_id=?`).bind(String(o.status||'active'),String(o.id||''),periodEnd,customer).run()}
 if(event.type==='customer.subscription.deleted'||event.type==='invoice.payment_failed'){const o=event.data.object;const customer=String(o.customer||'');await env.DB.prepare(`UPDATE users SET subscription_status=?,updated_at=CURRENT_TIMESTAMP WHERE stripe_customer_id=?`).bind(event.type==='customer.subscription.deleted'?'canceled':'past_due',customer).run()}return json({received:true})}
 return err('Not found.',404)
}catch(e){if(e instanceof Response)return e;console.error(e);return err(e.message||'Server error',500)}}
