create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null unique,full_name text,company_name text,phone text,country text,role text not null default 'user' check(role in('user','admin')),status text not null default 'trial' check(status in('trial','active','suspended')),plan text not null default 'Starter' check(plan in('Starter','Business','Pro','Enterprise')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.demo_requests(id uuid primary key default gen_random_uuid(),name text not null,email text not null,company_name text,message text,status text not null default 'new' check(status in('new','contacted','closed')),created_at timestamptz not null default now());
create table if not exists public.newsletter_subscribers(id uuid primary key default gen_random_uuid(),email text not null unique,created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,email,full_name,company_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'company_name');return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin');$$;
alter table public.profiles enable row level security;alter table public.demo_requests enable row level security;alter table public.newsletter_subscribers enable row level security;
drop policy if exists "profiles read" on public.profiles;create policy "profiles read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists "profiles update own" on public.profiles;create policy "profiles update own" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create or replace function public.admin_update_profile(target_id uuid,new_plan text default null,new_status text default null) returns public.profiles language plpgsql security definer set search_path='' as $$declare result public.profiles;begin if not public.is_admin() then raise exception 'Admin access required';end if;update public.profiles set plan=coalesce(new_plan,plan),status=coalesce(new_status,status),updated_at=now() where id=target_id returning * into result;return result;end;$$;
drop policy if exists "demo insert" on public.demo_requests;create policy "demo insert" on public.demo_requests for insert to anon,authenticated with check(true);
drop policy if exists "demo admin read" on public.demo_requests;create policy "demo admin read" on public.demo_requests for select to authenticated using(public.is_admin());
drop policy if exists "newsletter insert" on public.newsletter_subscribers;create policy "newsletter insert" on public.newsletter_subscribers for insert to anon,authenticated with check(true);
drop policy if exists "newsletter admin read" on public.newsletter_subscribers;create policy "newsletter admin read" on public.newsletter_subscribers for select to authenticated using(public.is_admin());
grant usage on schema public to anon,authenticated;grant insert on public.demo_requests to anon,authenticated;grant insert on public.newsletter_subscribers to anon,authenticated;revoke update on public.profiles from authenticated;grant update(full_name,company_name,phone,country,updated_at) on public.profiles to authenticated;grant execute on function public.admin_update_profile(uuid,text,text) to authenticated;grant select on public.demo_requests to authenticated;grant select on public.newsletter_subscribers to authenticated;
-- After registering your admin account, run:
-- update public.profiles set role='admin',status='active',plan='Enterprise' where email='YOUR-EMAIL';
